name: pc2beam
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - open3d
  - plotly
  - scikit-learn
  - omegaconf
  - matplotlib
  - tqdm
  - ifcopenshell=0.8.3.post1
  - helios=2.1.0
  - laspy
  - ipykernel
  - pip
  - pip:
      - -e .
