# Default configuration for PC2Beam

# S1 feature computation parameters
s1:
  radius: 0.25
  k: 30
  use_radius: true

# S2 feature computation parameters
s2:
  distance_threshold: 0.01
  ransac_n: 3
  num_iterations: 1000

# Visualization parameters
visualization:
  normal_length: 0.1
  max_points: 10000
  width: 1000
  height: 800

# Processing parameters
processing:
  min_points_per_instance: 50 