# default configuration for pc2beam

# s1 computation parameters
s1:
  radius: 0.25
  k: 30
  use_radius: true

# s2 estimationparameters
s2:
  distance_threshold: 0.02
  ransac_n: 3
  num_iterations: 1000

# visualization parameters
visualization:
  normal_length: 0.1
  max_points: 10000
  width: 800
  height: 600
  ortho_view: true

# processing parameters
processing:
  min_points_per_instance: 50